"""Update tables

Revision ID: 3c774f6dc6c4
Revises: 97d1e174f9be
Create Date: 2024-04-25 11:49:51.600951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c774f6dc6c4'
down_revision = '97d1e174f9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('directions', sa.Text(), nullable=False),
    sa.Column('total_servings', sa.Integer(), nullable=False),
    sa.Column('prep_time', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('cuisine_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], name=op.f('fk_recipes_cuisine_id_cuisines')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_cuisine',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.Column('user_attribute', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], name=op.f('fk_recipe_cuisine_cuisine_id_cuisines')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_cuisine_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('recipe_id', 'cuisine_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_cuisine')
    op.drop_table('recipes')
    op.drop_table('users')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
